server:
  bind: 0.0.0.0
  port: 5000
  uploads: .uploads
  public:
    - ^/$
    - ^/api/_system/stats

cors:
  origins: "*"
  methods: [ "GET", "POST", "PUT", "DELETE" ]
  allow_headers: [ "Content-Type", "Authorization" ]